apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: nagao-rolling-upgrade-simple-api
spec:
  params:
    - name: gitRepositoryManagerFQDN
      description: Git host like github.com or bitbucket.org
    - name: gitOrganization
      description: Git organization name
    - name: gitRepository
      description: Git source code repository name
    - name: gitRevision
      description: Git source revision
    - name: secretNameGitToken
      description: Git token sercret name
    - name: appConfigPath
      description: Path to application config
    - name: secretNameKubeconfig
      description: Kubeconfig secret name
    - name: namespace
      description: Kubernetes Namespace
    - name: imageName
      description: Image name of application
    - name: appName
      description: Application Name of Qmonus Value Stream
    - name: deployName
      description: Deployment Name of Qmonus Value Stream
  workspaces:
    - name: shared
  tasks:
    - name: checkout
      taskRef:
        name: git-checkout
      workspaces:
        - name: shared
          workspace: shared
      params:
        - name: gitOrganization
          value: $(params.gitOrganization)
        - name: gitRepository
          value: $(params.gitRepository)
        - name: gitRepositoryManagerFQDN
          value: $(params.gitRepositoryManagerFQDN)
        - name: gitRevision
          value: $(params.gitRevision)
        - name: secretNameGitToken
          value: $(params.secretNameGitToken)
    - name: compile-designpattern
      taskRef:
        name: compile-designpattern-simple-api
      workspaces:
        - name: shared
          workspace: shared
      runAfter:
        - checkout
      params:
        - name: appConfigPath
          value: $(params.appConfigPath)
        - name: namespace
          value: $(params.namespace)
        - name: imageName
          value: $(params.imageName)
    - name: deploy
      taskRef:
        name: deploy-to-k8s
      workspaces:
        - name: shared
          workspace: shared
      runAfter:
        - compile-designpattern
      params:
        - name: appName
          value: $(params.appName)
        - name: deployName
          value: $(params.deployName)
        - name: secretNameKubeconfig
          value: $(params.secretNameKubeconfig)
