apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: docker-login-acr
spec:
  params:
  - name: env
    description: Environment name
  - name: registryName
    description: Azure Container Registry name
  workspaces:
  - name: shared
  steps:
  - name: docker-login
    image: docker
    command:
    - /bin/sh
    - -c
    args:
    - docker --config=$(workspaces.shared.path)/dockerconfig login $(params.registryName).azurecr.io --username $(APP_ID) --password '$(PASSWORD)'
    env:
    - name: APP_ID
      valueFrom:
        secretKeyRef:
          name: $(params.env)-serviceprincipal
          key: appId
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: $(params.env)-serviceprincipal
          key: password
