apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: compile-designpattern-simple-api
spec:
  params:
    - name: pathToSource
      description: Relative path from source directory
      default: ""
    - name: appConfigPath
      description: Path to application config
    - name: namespace
      description: Kubernetes Namespace
    - name: imageName
      description: Image name of application
  workspaces:
    - name: shared
  steps:
    - name: make-params-json
      image: python
      script: |-
        #!/usr/bin/env python3
        import json
        params = []
        params.append({'name': 'namespace', 'value': '$(params.namespace)'})
        params.append({'name': 'imageName', 'value': '$(params.imageName)'})
        print(json.dumps({'params': params}, indent=4))
        open('$(workspaces.shared.path)/params.json', 'w').write(json.dumps({'params': params}, indent=4))
      workingDir: $(workspaces.shared.path)/source/$(params.pathToSource)
    - name: compile
      image: asia.gcr.io/axis-gcp-dev-46876560/config-compiler:v0.7.0
      args:
        - manifest
        - -o
        - $(workspaces.shared.path)/manifests/manifests.yaml
        - -c
        - $(params.appConfigPath)
        - -p
        - $(workspaces.shared.path)/params.json
      workingDir: $(workspaces.shared.path)/source
