apiVersion: vs.axis-dev.io/v1
kind: AssemblyLine
metadata:
  name: nagao-staging-deploy
spec:
  params:
    - name: gitRevision
      type: string
    - name: imageName
      type: string
  stages:
    - name: deploy
      spec:
        pipeline: nagao-rolling-upgrade-simple-api
        deployment:
          app: nagao-simple-api
          name: nagao-deployment
        params:
          - name: gitRevision
            value: $(inputs.gitRevision)
          - name: imageName
            value: $(inputs.imageName)
